.TH DVDISASTER 1 "2005-11-25" "0.64.2" "protection for CD/DVD media"

.SH NOME
DVDISASTER \- data loss/scratch/aging protection for CD/DVD media

.SH SINTASSI
.B dvdisaster
.RB [\| \-r \||\| \-c \||\| \-f \||\| \-s \||\| \-t \||\| \-u \|]
.RB [\| \-d
.IR device \|]
.RB [\| \-p
.IR prefix \|]
.RB [\| \-i
.IR image \|]
.RB [\| \-e
.IR eccfile \|]
.RB [\| \-j
.IR n \|]
.RB [\| -n
.IR n% \|]
.RB [\| \-\-adaptive-read \|]
.RB [\| \-\-auto-suffix \|]
.RB [\| \-\-cache-size
.IR n \|]
.RB [\| \-\-dao \|]
.RB [\| \-\-fill-unreadable
.IR n \|]
.RB [\| \-\-speed-warning
.IR n \|]
.RB [\| \-\-spinup\-dalay
.IR n \|]
.RB [\| \-\-split\-files \|]

.SH DESCRIZIONE
.B DVDISASTER
offre un margine di sicurezza contro la perdita di dati dei supporti CD e DVD
causata dall'invecchiamento e dai graffi. Crea dei dati di correzione degli
errori che saranno poi utilizzati per recuperare i settori illeggibili se il
supporto dovesse danneggiarsi col tempo.
.PP

.SH OPZIONI
Tipici esempi di utilizzo:
.TP
.B \-r, \-\-read
Estrae l'immagine del supporto sull'hard disc. Usare -rn-m per leggere un
determinato intervallo di settori, ad es. -r100-200.
.TP
.B \-c, \-\-create
Crea l'informazione .ecc per l'immagine del supporto.
.TP
.B \-f, \-\-fix
Prova a correggere l'immagine del supporto usando l'informazione .ecc.
.TP
.B \-s, \-\-scan
Scansiona il supporto per gli errori di lettura.
.TP
.B \-t, \-\-test
Testa l'integrit\[`a] dei file .img e .ecc.
.TP
.B \-u, \-\-unlink
Cancella i file .img (Quando le altre azioni sono concluse).
.PP

Specifiche drive e file:
.TP
.B \-d, \-\-device device
Legge dalla periferica specificata (Standard: /dev/cdrom).
.TP
.B \-p, \-\-prefix prefix
Prefisso del file .img/.ecc (Standard: medium.* ).
.TP
.B \-i, \-\-image imagefile
Nome del file immagine (Standard: medium.img).
.TP
.B \-e, \-\-ecc eccfile
Nome del file di Parit\[`a] (Standard: medium.ecc).
.PP

Opzioni per "smanettoni" (Leggere il manuale prima di utilizzarle!):
.TP
.B \-j, \-\-jump n
Salta n settori in avanti dopo un errore di lettura (Standard: 16).
.TP
.B \-n, \-\-redundancy n%
Setta la ridondanza per la correzione degli errori (Standard: 14.3%).
.TP
.B \-\-adaptive-read
usare la strategia ottimizzata per leggere i supporti danneggiati.
.TP
.B \-\-auto-suffix
aggiungi automaticamente i suffissi .img e .ecc.
.TP
.B \-\-cache-size n
Dimensione della cache in MB con la modalit\[`a] -c (Standard: 32MB).
.TP
.B \-\-dao
Utilizza la modalit\[`a] DAO; Il disco non sar\[`a] finalizzato.
.TP
.B \-\-fill-unreadable n
Riempi i settori illeggibili con il byte n.
.TP
.B \-\-speed-warning n
Evidenzia messaggio di ATTENZIONE se la velocit\[`a] cambia pi\[`u] del n
percento.
.TP
.B \-\-spinup-delay n
Attendere n secondi per far avviare il drive.
.TP
.B \-\-split-files
Suddividere l'immagine in file <= 2GB.
.PP


.SH "VEDERE ANCHE"
.B Documentation
DVDISASTER is documented by its own manual, installed in
.IR %docdir%

.SH AUTORI
DVDISASTER was written by Carsten Gnoerlich <carsten@dvdisaster.com>.
.PP
This manual page was written by Daniel Baumann
<daniel.baumann@panthera-systems.net>, for the Debian project (but may be used
by others).
