.TH DVDISASTER 1 "2010-10-31" "0.72" "Schutz f\[:u]r CD/DVD Medien"

.SH NAME
DVDISASTER \- Schutz f\[:u]r CD/DVD Medien gegen Datenverlust durch Alterung
oder Kratzer

.SH SYNTAX
.B dvdisaster
.RB [\| \-r \||\| \-c \||\| \-f \||\| \-s \||\| \-t \||\| \-u \|]
.RB [\| \-d
.IR device \|]
.RB [\| \-p
.IR prefix \|]
.RB [\| \-i
.IR image \|]
.RB [\| \-e
.IR eccfile \|]
.RB [\| \-\-list \|]
.RB [\| \-j
.IR n \|]
.RB [\| -n
.IR n% \|]
.RB [\| -m
.IR n \|]
.RB [\| -v \|]
.RB [\| \-\-adaptive-read \|]
.RB [\| \-\-auto-suffix \|]
.RB [\| \-\-cache-size
.IR n \|]
.RB [\| \-\-dao \|]
.RB [\| \-\-driver
.IR d \|]
.RB [\| \-\-eject \|]
.RB [\| \-\-fill-unreadable
.IR n \|]
.RB [\| \-\-ignore-fatal-sense \|]
.RB [\| \-\-internal-rereads
.IR n \|]
.RB [\| \-\-query-size
.IR n \|]
.RB [\| \-\-raw-mode
.IR n \|]
.RB [\| \-\-read-attempts
.IR n-m \|]
.RB [\| \-\-read-medium
.IR n \|]
.RB [\| \-\-read-raw \|]
.RB [\| \-\-speed-warning
.IR n \|]
.RB [\| \-\-spinup\-dalay
.IR n \|]
.RB [\| \-\-split\-files \|]

.SH BESCHREIBUNG
.B DVDISASTER
erzeugt einen Sicherheitspuffer gegen Datenverluste, die auf CD- und
DVD-Datentr\[:a]gern durch Alterung oder Kratzer entstehen. Es erzeugt
Fehlerkorrekturdaten, um bei nachfolgenden Datentr\[:a]ger-Problemen unlesbare
Sektoren zu rekonstruieren.

.SH TYPISCHE ANWENDUNGEN

.TP
\fBdvdisaster\fP \fB-d\fP \fI/dev/hdc\fP \fB-s\fP
\[:U]berpr\[:u]ft den Datentr\[:a]ger in Laufwerk \fI/dev/hdc\fP auf Fehler.
.TP
\fBdvdisaster\fP \fB-d\fP \fI/dev/hdc\fP \fB-i\fP \fIabbild.iso\fP \fB-r\fP
Erstellt ein Abbild vom Datentr\[:a]ger in Laufwerk \fI/dev/hdc\fP als Datei \fIabbild.iso\fP.
.TP
\fBdvdisaster\fP \fB-d\fP \fI/dev/hdc\fP \fB-i\fP \fImedium.iso\fP \fB--read-raw\fP \fB-r\fP
Erstellt ein Abbild wie oben beschrieben. Die Sektoren werden anhand ihrer
EDC- und L-EC-Rohdaten auf Unversehrtheit \[:u]berpr\[:u]ft. Dies ist nur f\[:u]r 
CD-Datentr\[:a]ger m\[:o]glich; anderenfalls hat die \fB--read-raw\fP-Option
keine Wirkung.
.TP
\fBdvdisaster\fP \fB-d\fP \fI/dev/hdc\fP \fB-i\fP \fImedium.iso\fP \fB--read-attempts\fP \fIn-m\fP \fB-r\fP
Erstellt ein Abbild wie oben beschrieben. F\[:u]r besch\[:a]digte Sektoren werden
mindestens \fIn\fP und h\[:o]chstens \fIm\fP Leseversuche unternommen. Die
Lesbarkeit von besch\[:a]digten CD-Datentr\[:a]gern kann in Verbindung mit
\fB--read-raw\fI besser werden.
.TP
\fBdvdisaster\fP \fB-d\fP \fI/dev/hdc\fP \fB-i\fP \fIabbild.iso\fP \fB-e\fP \fIkorr.ecc\fP \fB-r\fP \fB--adaptive-read\fP
Verwendet die angepasste Lesestrategie, um ein Abbild vom 
Datentr\[:a]ger in Laufwerk \fI/dev/hdc\fP als Datei \fIabbild.iso\fP
zu erstellen. Der Lesevorgang wird automatisch beendet
sobald gen\[:u]gend Daten eingelesen wurden, um das Abbild mit Hilfe der 
Fehlerkorrektur-Datei \fIkorr.ecc\fP wiederherzustellen:
.TP
\fBdvdisaster\fP \fB-i\fP \fIabbild.iso\fP \fB-e\fP \fIkorr.ecc\fP \fB-c\fP
Erzeugt eine Fehlerkorrektur-Datei \fIkorr.ecc\fP f\[:u]r das Abbild \fIabbild.iso\fP.
.TP
\fBdvdisaster\fp \fB-i\fP \fIabbild.iso\fP \fB-m\fIRS02\fP \fB-n\fP \fI350000\fP \fB-c\fP
Erweitert ein Abbild \fIabbild.iso\fP mit Fehlerkorrektur-Daten,
wobei das Abbild auf nicht mehr als \fI350000\fP Sektoren vergr\[:o]ssert wird.
Ohne Angabe von \fB-n\fP wird das Abbild auf die Gr\[:o]sse des 
kleinstm\[:o]glichen Datentr\[:a]gers (CD, DVD, DVD9) erweitert.
Beachten Sie das fehlende Leerzeichen zwischen \fB-m\fP und \fIRS02\fP.
.TP
\fBdvdisaster\fP \fB-i\fP \fIabbild.iso\fP \fB-e\fP \fIkorr.ecc\fP \fB-f\fP
Wiederherstellung der Abbild-Datei \fIabbild.iso\fP 
mit Hilfe der Fehlerkorrektur-Datei \fIkorr.ecc\fP.
.TP
\fBdvdisaster\fP \fB-i\fP \fIabbild.iso\fP \fB-e\fP \fIkorr.ecc\fP \fB-t\fP
\[:U]berpr\[:u]ft den Inhalt des Abbilds \fIabbild.iso\fP 
mit Hilfe der Fehlerkorrektur-Datei \fIkorr.ecc\fP auf Vollst\[:a]ndigkeit und Korrektheit.
.TP
\fBHINWEIS:\fP
Geben Sie in den obigen Beispielen  die \fB-e korr.ecc\fP-Optionen nicht an, 
wenn Sie mit erweiterten Abbildern arbeiten.

.SH OPTIONEN
Aktions-Auswahl (mindestens eine Aktion muss gew\[:a]hlt werden):
.TP
.B \-r, \-\-read
Datentr\[:a]ger-Abbild auf Festplatte einlesen. -rn-m liest einen Bereich von
Sektoren, z.B. -r100-200.
.TP
.B \-c, \-\-create
Erzeugt Fehlerkorrektur-Daten f\[:u]r das Abbild.
.TP
.B \-f, \-\-fix
Versucht das Abbild mit Hilfe der Fehlerkorrektur-Daten zu reparieren.
.TP
.B \-s, \-\-scan
Untersucht den Datentr\[:a]ger auf Lesefehler.
.TP
.B \-t, \-\-test
Pr\[:u]ft die Struktur der .iso und .ecc - Dateien.
.TP
.B \-u, \-\-unlink
L\[:o]scht .iso - Dateien nach Beenden der vorherigen Aktionen.
.PP

Laufwerks- und Dateinamen:
.TP
.B \-d, \-\-device device
Von diesem Laufwerk lesen (Standard: /dev/cdrom).
.TP
.B \-p, \-\-prefix prefix
Anfang der .iso/.ecc - Dateien (Standard: medium.* ).
.TP
.B \-i, \-\-image imagefile
Name der Abbild - Datei (Standard: medium.iso).
.TP
.B \-e, \-\-ecc eccfile
Name der Fehlerkorrektur-Datei (Standard: medium.ecc).
.PP
.B \-\-list
Zeigt verf\[:u]gbare Laufwerke unter dem ASPI-Treiber (nur f\[:u]r Windows).
.PP

Feineinstellung (Beachten Sie die Hinweise in der Dokumentation!):
.TP
.B \-j, \-\-jump n
\[:u]berspringe n Sektoren nach einem Lesefehler (Standard: 16).
.TP
.B \-n, \-\-redundancy n[unit]
Redundanz der Fehlerkorrektur-Daten. Die zulässigen Werte sind vom
verwendeten Kodierer abhängig:

.RS
RS01-Fehlerkorrektur-Dateien:
.RS
\-n x\ \ erzeugt Fehlerkorrektur-Datei mit x Nullstellen.
.RE
.RS
\-n x% erzeugt Fehlerkorrektur-Datei mit x Prozent Redundanz.
.RE
.RS
\-n xm erzeugt Fehlerkorrektur-Datei mit ca. x MB Größe.
.RE
.RS 
\-n normal - optimierter Kodierer für 14.3% Redundanz/32 Nullstellen.
.RE
.RS
\-n high\ \ \ - optimierter Kodierer für 33.5% Redundanz/64 Nullstellen.
.RE
.RE

.RS
RS02-Abbilder:
.RS
\-n CD\ \ \ erweitert Abbild auf CD-Größe.
.RE
.RS
\-n DVD\ \ erweitert Abbild auf DVD-Größe.
.RE
.RS
\-n DVD9 erweitert Abbild auf DVD9-Größe.
.RE
.RS
\-n BD\ \ \ erweitert Abbild auf BD-Größe.
.RE
.RS
\-n BD2\  erweitert Abbild auf zweilagige BD-Größe.
.RE
.RS
\-n x\ \ \ \ erweitert Abbild auf ca. x Sektoren Länge.
.RE
.RS
\-n x%\ \ \ erweitert Abbild mit ca. x% Redundanz. 
.RE
.RS
\-n xr\ \ \ erweitert Abbild mit x Nullstellen Fehlerkorrektur-Daten.
.RE
.RE
.TP
.B \-m, \-\-method n
Fehlerkorrektur-Methoden anzeigen/ausw\[:a]hlen (Standard: RS01).
.RS
M\[:o]gliche Werte sind RS01 und RS02.
.RE
.TP
.B \-v, \-\-verbose n%
mehr erl\[:a]uternde Ausgaben
.TP
.B \-\-adaptive-read
verwende optimierte Lesestrategie f\[:u]r defekte Datentr\[:a]ger.
.TP
.B \-\-auto-suffix
automatisches Anf\[:u]gen der .iso- und .ecc-Dateiendungen.
.TP
.B \-\-cache-size n
Zwischenspeicher in MB bei .ecc-Datei-Erzeugung - (Standard: 32MB).
.TP
.B \-\-dao
unterstelle DAO; Abbild am Ende nicht k\[:u]rzen.
.TP
.B \-\-driver d (nur Linux)
W\[:a]hlt zwischen dem cdrom (CDROM_SEND_PACKET)-Treiber und dem
sg (SG_IO)-Treiber für die Laufwerke aus. Zur Zeit wird noch
der \[:a]ltere cdrom-Treiber als Voreinstellung verwendet; ab
dvdisaster 0.80 wird der neuere sg-Treiber die Standardauswahl.
Beide Treiber sollten gleich gut funktionieren.
.TP
.B \-\-eject
Datentr\[:a]ger nach erfolgreichem Lesen auswerfen.
.TP
.B \-\-fill-unreadable n
f\[:u]lle unlesbare Sektoren mit Byte n.
.TP
.B \-\-ignore-fatal-sense
Lesen nach m\[:o]glicherweise schwerwiegenden Fehlern fortsetzen.
.TP
.B \-\-internal-rereads n
Leseversuche innerhalb des Laufwerks f\[:u]r besch\[:a]digte CD-Sektoren (Standard: -1)
.RS
Laufwerke unternehmen normalerweise mehrere Versuche um einen besch\[:a]digten Sektor 
zu lesen. Es ist typischerweise g\[:u]nstiger diesen Wert auf 0 oder 1 zu setzen
und die Anzahl der Leseversuche \[:u]ber den Parameter --read-attempts zu steuern.
Viele Laufwerke ignorieren diese Einstellung ohnehin. Benutzen Sie den Wert -1 um 
die Standardeinstellungen des Laufwerks zu verwenden.
.RE
.TP
.B \-\-query-size n
Ermittelt die Abbildgr\[:o]sse durch das Laufwerk oder das Dateisystem auf dem Datentr\[:a]ger
(Standard: ecc)
.RS
M\[:o]gliche Werte: drive udf ecc 
.RE
.TP
.B \-\-raw-mode n
"Raw"-Lese-Verfahren f\[:u]r besch\[:a]digte CD-Sektoren (default: 20)
.RS
Das empfohlene Verfahren ist 20, bei dem das Laufwerk die eingebaute Fehlerkorrektur
so weit wie m\[:o]glich anwendet, bevor es einen besch\[:a]digten Sektor 
zur\[:u]ckgibt. Einige Laufwerke k\[:o]nnen besch\[:a]digte Sektoren allerdings
nur in der Betriebsart 21 lesen. Dabei wird die letzte Stufe der eingebauten
Fehlerkorrektur nicht ausgef\[:u]hrt und der Sektor wird unkorrigiert
zur\[:u]ckgegeben.
.RE
.TP
.B \-\-read-attempts n-m
versucht einen besch\[:a]digten Sektor n bis m-mal zu lesen.
.TP
.B \-\-read-medium n
liest den gesamten Datentr\[:a]ger bis zu n-mal.
.TP
.B \-\-read-raw
liest in der "raw"-Betriebsart sofern m\[:o]glich.
.TP
.B \-\-speed-warning n
warnt bei Geschwindigkeits\[:a]nderung um mehr als n Prozent.
.TP
.B \-\-spinup-delay n
gibt dem Laufwerk n Sekunden Zeit zum Hochlaufen.
.TP
.B \-\-split-files
Abbild in mehrere Dateien <= 2GB aufteilen.
.PP

.SH SIEHE AUCH
.B Dokumentation
DVDISASTER ist in seinem eigenen Handbuch dokumentiert, welches in
.IR %docdir%
installiert ist.

.SH AUTHOR
DVDISASTER wurde von Carsten Gnoerlich <carsten@dvdisaster.com> geschrieben.
.PP
Diese Hilfeseite wurde von Daniel Baumann <daniel.baumann@panthera-systems.net>
f\[:u]r das Debian Projekt geschrieben (kann aber auch von Anderen verwendet
werden). Sie wurde f\[:u]r Version 0.70/0.72 von Carsten Gn\[:o]rlich erweitert.
